from __future__ import annotations

from enum import StrEnum


class EngagementState(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    ATTORNEY_APPROVAL_RECORDED = "ATTORNEY_APPROVAL_RECORDED"
    CONFLICT_REVIEW_PENDING = "CONFLICT_REVIEW_PENDING"
    CONFLICT_HOLD = "CONFLICT_HOLD"
    PACKAGE_PREPARATION = "PACKAGE_PREPARATION"
    DELIVERY_AUTHORIZED = "DELIVERY_AUTHORIZED"
    DELIVERED = "DELIVERED"
    CLIENT_REVIEW = "CLIENT_REVIEW"
    SIGNATURE_PENDING = "SIGNATURE_PENDING"
    FULLY_EXECUTED = "FULLY_EXECUTED"
    ACTIVATION_PENDING = "ACTIVATION_PENDING"
    ACTIVATED = "ACTIVATED"
    DECLINED_OR_EXPIRED = "DECLINED_OR_EXPIRED"
